### ISSUE TITLE
Build fail with v1.5.0

### ISSUE THREAD

**Issue by jpvalery** [TryGhost/gatsby-plugin-advanced-sitemap#17]
### Issue Summary

CI/CD with GH Actions encounters an issue during build
![image](https://user-images.githubusercontent.com/4112343/74243253-6a9dc880-4cad-11ea-9197-eb4711e78c55.png)
https://github.com/MontrealPhotoClub/montrealphotoclub.en/pull/121/checks?check_run_id=438650317

```
 ERROR #11321  PLUGIN

"gatsby-plugin-advanced-sitemap" threw an error while running the onPostBuild lifecycle:

additionalSitemaps.forEach is not a function

  186 |
  187 |   if (additionalSitemaps) {
> 188 |     additionalSitemaps.forEach(function (addSitemap, index) {
      |                        ^
  189 |       if (!addSitemap.url) {
  190 |         throw new Error("URL is required for additional Sitemap: ", addSitemap);
  191 |       }

File: node_modules/gatsby-plugin-advanced-sitemap/gatsby-node.js:188:24

error Command failed with exit code 1.
```
### To Reproduce

1. Try to build with v1.5.0
2. Get an error "additionalSitemaps.forEach is not a function"

### Technical details:

* Gatsby Version: 2.19.12

**Comment by AileenCGN** [comment]
Ouch.. good catch. Fix coming in a sec 😬

**Comment by AileenCGN** [comment]
Just published the fix! Please let me know if it's not fixed by that! And thanks for the quick report 😊

**Comment by jpvalery** [comment]
Pleasure is all mine! Thanks for the quick fix ;) 

CI workflows are running, will let you know if they fail 🤘

**Comment by jpvalery** [comment]
All good 💯
