### ISSUE TITLE
Peer dependency compatibility with Gatsby 4.0

### ISSUE THREAD

**Issue by broksonic21** [TryGhost/gatsby-plugin-advanced-sitemap#199]
### Issue Summary

Gatsby 4.0 is out but gatsby-plugin-advanced-sitemap restricts the peer dependency to 3.0. This blocks running npm audit fix, amongst other projects. Is there a plan to update? Looks like renovate is trying to at https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/pull/198

### To Reproduce

See https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/master/package.json#L32

1. have a package.json with Gatsby 4.0 and gatsby-plugin-advanced-sitemap 2.0
2. run `npm audit fix` (using node 16)
3. see it complain on mismatch on peer dependency

### Technical details:

* Gatsby Version: 4.0
* Node Version: 16.11.1
* OS: Mac

**Comment by broksonic21** [comment]
is there an update on a new version for this?

**Comment by gauthamilango** [comment]
Is anyone working on this?

**Comment by julrich** [comment]
Also waiting for this! :eyes: 
So far it's working flawlessly (as far as I can judge that) for us on `v4`, it's just the warning!

**Comment by hisnameisjimmy** [comment]
Also would love this!

**Comment by simon-abbott** [comment]
I can confirm that it breaks with gatsby `4.4.0` because it's using `pify`, but not declaring it as a dependency.

https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/5a7efa130e3f6e64e7f04e582b1fa9cef9dd0bc1/src/utils.js#L2

https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/5a7efa130e3f6e64e7f04e582b1fa9cef9dd0bc1/package.json#L50-L56

**Comment by Hahlh** [comment]
@simon-abbott Could you please speficy in what way it exactly breaks in your case?

I have currently brought a project up to 4.5.2 and despite the compability warning, the plugin still seems to correctly generate the sitemaps in my case.

**Comment by nazzart** [comment]
@Hahlh , I have same issue. It doesnt work with gatsby 4.2. 
The error message I get durring the build is:
` Error: Cannot find module 'pify'`
`Plugin gatsby-plugin-advanced-sitemap is not compatible with your gatsby version 4.2.0 - It requires gatsby@^3.0.0
`

**Comment by thibaultcrouzet** [comment]
`warn Plugin gatsby-plugin-advanced-sitemap is not compatible with your gatsby version 4.5.5 - It requires gatsby@^3.0.0`
any update soon?

**Comment by tony** [comment]
There is a new package: [`gatsby-plugin-complex-sitemaps`](https://github.com/Chefclub/gatsby-plugin-complex-sitemaps)

Haven't tried it yet, but there's a [migration guide from gatsby-plugin-advanced-sitemap](https://github.com/Chefclub/gatsby-plugin-complex-sitemaps/blob/master/docs/advanced-sitemap-migration.md)

**Comment by yogeshkotadiya** [comment]
Fixed in release v2.1.0:  #178
